[package]
name = "native-launcher"
version = "0.1.0"
edition = "2021"
workspace = "../.."

[dependencies]
bevy_bird = { package = "bevy_bird", path = "../.." }
bevy = "0.14"
image = "0.24.9"
winit = "0.26.1"