[package]
name = "native-launcher"
version = "0.1.0"
edition = "2021"
workspace = "../.."

[dependencies]
bevy_bird = { package = "bevy_bird", path = "../.." }
bevy = "0.8"
image = "0.25.0"
winit = "0.26.1"